version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "monthly"
  # Lotus still decodes legacy state with v2
  - package-ecosystem: "gomod"
    target-branch: "release/v2"
    directories:
      - "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    target-branch: "release/v2"
    directories:
      - "/"
    schedule:
      interval: "monthly"
